version: 0.2
env:
  variables: {}
phases:
  install:
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - "export DOCKER_IMAGE_URL=${DOCKER_REPOSITORY_URL}:${CODEBUILD_RESOLVED_SOURCE_VERSION}"
  build:
    commands:
      - "docker build --tag $DOCKER_IMAGE_URL ."
  post_build:
    commands:
      - $(aws ecr get-login)
      - docker push $DOCKER_IMAGE_URL
      - 'echo "{\"imageUrl\": \"$DOCKER_IMAGE_URL\"}" > buildOutputs.json'
      - echo Pushed image to $DOCKER_IMAGE_URL
artifacts:
  discard-paths: yes
  files:
    - "src/main/cloudformation/*"
    - "buildOutputs.json"