AWSTemplateFormatVersion: "2010-09-09"
Description: "CI/CD Pipeline for the times-two service. (prowe)"
Parameters:
  RepoToken:
    Type: String
    Description: OAuth Token for the repo
Resources:
  ArtifactStorage:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties: {}
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: "sts:AssumeRole"
              Principal:
                Service: "codepipeline.amazonaws.com"
            - Effect: "Allow"
              Action: "sts:AssumeRole"
              Principal:
                Service: "codebuild.amazonaws.com"
            - Effect: "Allow"
              Action: "sts:AssumeRole"
              Principal:
                Service: "cloudformation.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  BuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - PipelineRole
    Properties:
      Name: timesTwo
      ServiceRole: !GetAtt PipelineRole.Arn
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        EnvironmentVariables:
          - Name: DOCKER_REPOSITORY_URL
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerRepo}"
      Artifacts:
        Type: CODEPIPELINE
  DockerRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !GetAtt PipelineRole.Arn
            Action: 
              - "ecr:*"
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - PipelineRole
      - BuildProject
    Properties:
      ArtifactStore: 
        Type: "S3"
        Location: !Ref ArtifactStorage
      RoleArn: !GetAtt PipelineRole.Arn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source 
              Provider: GitHub
              Owner: ThirdParty 
              Version: 1 
            OutputArtifacts:
              - Name: sourceCode
            Configuration:
              Owner: "prowe"
              Repo: "times-two"
              Branch: master
              OAuthToken: !Ref RepoToken
        - Name: Build
          Actions:
          - Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: sourceCode
            Configuration:
              ProjectName: timesTwo
            OutputArtifacts:
              - Name: buildResults
        - Name: Deploy_DEV
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: buildResults
            Configuration:
              RoleArn: !GetAtt PipelineRole.Arn
              StackName: !Sub '${AWS::StackName}-DEV'
              ActionMode: REPLACE_ON_FAILURE
              TemplatePath: !Sub "buildResults::application.template.yaml"